defmodule Symphony.Run do
  @derive Jason.Encoder
  defstruct issue_id: nil,
            issue_identifier: nil,
            workspace_path: nil,
            session_id: nil,
            started_at: nil,
            last_event_at: nil,
            last_event: nil,
            last_message: nil,
            status: :queued,
            phase: "build",
            issue: nil,
            agent_profile: nil,
            attempt: nil,
            refiner_attempt: 0,
            refiner_max_attempts: nil,
            judge_verdict: nil,
            score_path: nil,
            score_summary: nil,
            phase_history: [],
            conversation: [],
            turn_count: 0,
            tokens: %{input_tokens: 0, output_tokens: 0, total_tokens: 0},
            error: nil,
            events: [],
            prompt: nil
end
